apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginx-rc
spec:
  replicas: 2
  selector:
    app: mypod
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
        - name: first-container
          image: nginx
          ports:
            - containerPort: 80
